server:
  port: 8001

spring:
  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: metavirtual.bloom@gmail.com #앱 비밀번호 발급받은 google 계정
    password: egvf wfjq hgrb lexz #발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            auth: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.coffit.today:3306/bloom
    username: HIkdt6
    password: HIkdt6
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      location: D:/Blommmmm/

image:
  image-dir: img

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.metavirtual.bloom.user.model.dto
